package osu.beatmap.serialization;

import osu.beatmap.Beatmap;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

public class BeatmapSerializer {

    public static final String OSU_VERSION_FILE_HEADER = "osu file format v14\n";//\n\n// file generated by Ozu Beatmap Parser " + BeatmapParser.VERSION + "\n";


    public static void encode(Beatmap beatmap, Consumer<List<String>> fileGenerator) {
        fileGenerator.accept(convertToFileContent(beatmap));
    }

    private static List<String> convertToFileContent(Beatmap beatmap) {
        final List<String> fileContent = new ArrayList<>();

        fileContent.add(OSU_VERSION_FILE_HEADER);
        fileContent.addAll(beatmap.general.asFileContent());
        fileContent.addAll(beatmap.editor.asFileContent());
        fileContent.addAll(beatmap.metadata.asFileContent());
        fileContent.addAll(beatmap.difficulty.asFileContent());
        fileContent.addAll(beatmap.events.asFileContent());
        fileContent.addAll(beatmap.timingPoints.asFileContent());
        fileContent.addAll(beatmap.colours.asFileContent());
        fileContent.addAll(beatmap.hitObjects.asFileContent());

        return fileContent;
    }
}
